"""empty message

Revision ID: 34ba0464f99f
Revises: 611c80269098
Create Date: 2025-05-30 22:36:50.234460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ba0464f99f'
down_revision: Union[str, None] = '611c80269098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_operations', sa.Column('instrument_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('fk_balance_operations_ticker_instruments'), 'balance_operations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_balance_operations_instrument_id_instruments'), 'balance_operations', 'instruments', ['instrument_id'], ['id'])
    op.drop_column('balance_operations', 'ticker')
    op.add_column('balances', sa.Column('instrument_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('fk_balances_ticker_instruments'), 'balances', type_='foreignkey')
    op.create_foreign_key(op.f('fk_balances_instrument_id_instruments'), 'balances', 'instruments', ['instrument_id'], ['id'])
    op.drop_column('balances', 'ticker')
    op.add_column('instruments', sa.Column('id', sa.UUID(), nullable=False))
    op.create_index('uq_instruments_ticker_active', 'instruments', ['ticker'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('orders', sa.Column('instrument_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('fk_orders_ticker_instruments'), 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_instrument_id_instruments'), 'orders', 'instruments', ['instrument_id'], ['id'])
    op.drop_column('orders', 'ticker')
    op.add_column('transactions', sa.Column('instrument_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('fk_transactions_ticker_instruments'), 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transactions_instrument_id_instruments'), 'transactions', 'instruments', ['instrument_id'], ['id'])
    op.drop_column('transactions', 'ticker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_transactions_instrument_id_instruments'), 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transactions_ticker_instruments'), 'transactions', 'instruments', ['ticker'], ['ticker'])
    op.drop_column('transactions', 'instrument_id')
    op.add_column('orders', sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_orders_instrument_id_instruments'), 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_ticker_instruments'), 'orders', 'instruments', ['ticker'], ['ticker'])
    op.drop_column('orders', 'instrument_id')
    op.drop_index('uq_instruments_ticker_active', table_name='instruments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('instruments', 'id')
    op.add_column('balances', sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_balances_instrument_id_instruments'), 'balances', type_='foreignkey')
    op.create_foreign_key(op.f('fk_balances_ticker_instruments'), 'balances', 'instruments', ['ticker'], ['ticker'])
    op.drop_column('balances', 'instrument_id')
    op.add_column('balance_operations', sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_balance_operations_instrument_id_instruments'), 'balance_operations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_balance_operations_ticker_instruments'), 'balance_operations', 'instruments', ['ticker'], ['ticker'])
    op.drop_column('balance_operations', 'instrument_id')
    # ### end Alembic commands ###
