# Официальный пример использования uv в образах Docker
# https://github.com/astral-sh/uv-docker-example/
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder



# МОЖЕШЬ ОСОБО НЕ ВДАВАТЬСЯ В ПОДРОБНОСТИ
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_PYTHON_DOWNLOADS=0
# -------------------------------------------

WORKDIR /app


# МОЖЕШЬ ОСОБО НЕ ВДАВАТЬСЯ В ПОДРОБНОСТИ
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-dev
# -------------------------------------------

FROM python:3.12-slim-bookworm AS runtime

WORKDIR /app

COPY --from=builder /app/.venv /app/.venv

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app \
    PROMETHEUS_MULTIPROC_DIR=/tmp/metrics

RUN mkdir -p /tmp/metrics

COPY src ./src

EXPOSE 80

FROM runtime AS prod
ENTRYPOINT ["python", "src/run"]

FROM runtime AS celery
CMD ["celery", "-A", "src.api_v1.celery_module.celery_app:app", "worker", "--loglevel=info"]

FROM runtime AS celery-beat
CMD ["celery", "-A", "src.api_v1.celery_module.celery_app:app", "beat", "--loglevel=info"]